DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS task;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email_address TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  birthdate TIMESTAMP NOT NULL,
  first_name STRING NOT NULL,
  last_name STRING NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  status STRING NOT NULL,
  due_date TIMESTAMP NOT NULL,
  is_recurring BOOLEAN NOT NULL,
  recurring_type STRING NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);